### ISSUE TITLE
Does not work with Angular Universal

### ISSUE THREAD

**Issue by ndevnani** [Tealium/integration-angular#5]
Hello,

We are using Angular Universal and service code from this repository throws an error "Window is not defined". Could you please provide an example of utag service working with Angular Universal?

Thanks and Regards,
Naresh

**Comment by tygavin** [comment]
The utag.js and the majority of the client-side tags found in the Tealium iQ marketplace expect to run in a browser (where there is a DOM and a window object defined.)  But maybe you are looking for information on how to send data to Tealium's EventStream using the HTTP API? 

- https://community.tealiumiq.com/t5/Universal-Data-Hub/Tealium-Collect-HTTP-API/ta-p/16893
