### ISSUE TITLE
Tracking Calls are not sent

### ISSUE THREAD

**Issue by rkrz** [Tealium/integration-angular#6]
Hi!

I'm using the provided utag service in an Angular 6 app. On the page the utag.js file is loaded correctly and seems to run. When I call 

`this.TealiumUtagService.link({'page_type': 'trackEvent view called'});`

the underlying e.g. `window.utag.track('link', {page_type:"trackEvent view called"})` is also called, but I can't see any network requests being sent. Calling the `window.utag.track('link', {page_type:"trackEvent view called"})` in the dev-console does return true, but does not send anything neither.

Although the utag.js (I bundled a few tags here) gets delivered, no other bundles get loaded. Instead there is only a request for `http://tags.tiqcdn.com/utag/tiqapp/utag.v.js?a=[accountId]/[profileId]/201807021124&cb=1531380442945` - so instead of the tag UID a plain 'v' is used. The response for that is an empty file.

Let me know, if you need some more detailed information!

**Comment by tygavin** [comment]
This is most likely an issue with the Tag setup.  Keep in mind that the utag.link event is typically only supported for analytics vendors.  And some analytics tag vendors have required mappings in order for the request to go out.  

For example, the following "NOTE" in the documentation for Google Analytics.

"Events are only sent if both the Event Category and Event Action are defined."

These values must be set in mapping configuration for the tag and have values present in the data layer.

https://community.tealiumiq.com/t5/Tags/Google-Universal-Analytics-Tag-Advanced-Mapping/ta-p/11985#toc-hId-441700216

Hopefully this resolves the issue, if not, please reach out to Tealium's technical support team for further troubleshooting.

**Comment by rkrz** [comment]
I don't think that this is the issue, because when I run the same tag config with the angularjs version of my site, the calls are sent.

**Comment by tygavin** [comment]
Have you contacted your Account Manager or opened up a support ticket for some help with troubleshooting?

Some details to provide
- what is your account/profile
- what do you see in console with debugging enabled?  document.cookie="utagdb=true";
- url to reproduce the issue

**Comment by rkrz** [comment]
Thanks for your reply, I already found out that the issue was due to my specific TIQ configuration.

**Comment by fncmedia** [comment]
@rkrz  can you describe what has been your configuration issue?
