### ISSUE TITLE
Angular 4+ Tech Stack Compatible?

### ISSUE THREAD

**Issue by plearatblast** [Tealium/integration-angular#7]
We have a client that is currently developing in the Angular 4+ tech stack. We have found a Tealium guide on integrating the service within an Angular 2+ application.  Is the example below still a good use case? 
https://github.com/Tealium/integration-angular/blob/master/example/src/app/tealium/utag.service.ts
If not, are there better examples to follow?

**Comment by tygavin** [comment]
My expectation is this should still work fine with Angular 4.
