### ISSUE TITLE
used this repo to load utag.sync.js ; page refreshes when file is loaded.

### ISSUE THREAD

**Issue by hrishikeshpotdar91** [Tealium/integration-angular#9]
I followed the exact same way to load both these files. 

I'm loading utag.sync.js first in the head
then utag.js first thing in body. 

when utag.sync.js is loaded the page refreshes; when i load utag.js and skip the sync file everything works as expected.

**Comment by tygavin** [comment]
Most implementations do not need utag.sync.js (most tag vendors support asynchronous tagging these days). I would recommend using only utag.js.  This appears to be your resolution as well?

For more details on utag.sync.js implementation, please see: https://community.tealiumiq.com/t5/iQ-Tag-Management/Using-the-utag-sync-js-Script/ta-p/19175

Any specific questions regarding utag.sync.js implementation should be submitted [here](https://community.tealiumiq.com) or sent directly to your account manager.
